services:
  blog:
    image: cracktc/blog
    restart: always
    ports:
      - '8880:8880'
    volumes:
      - ./blog:/web/blog
      - ./config.json:/config.json
  redis:
    image: redis:alpine
    restart: always
